import { ChapterMeta } from './types'

export const chapters: ChapterMeta[] = [
  { slug: 'chuong-40', title: 'Chương 40: Bị Ngôi Sao Ruồng Bỏ | Abandoned by the Stars', chapterNumber: 40, arc: 6 },
  { slug: 'chuong-41', title: 'Chương 41 | The Scent of Peace', chapterNumber: 41, arc: 6 },
  { slug: 'chuong-42', title: 'Chương 42 | The Tower of the Dead', chapterNumber: 42, arc: 6 },
  { slug: 'chuong-43', title: 'Chương 43: Tòa Tháp Của Người Sống | The Tower of the Living', chapterNumber: 43, arc: 6 },
  { slug: 'chuong-44', title: 'Chương 44: Huy Chương Máu | Medal of Blood', chapterNumber: 44, arc: 6 },
  { slug: 'chuong-45', title: 'Chương 45: Vòng Tay Của Kẻ Có Tội | Embrace of The Guilty', chapterNumber: 45, arc: 6 },
  { slug: 'chuong-46', title: 'Chương 46: Meili Portroute', chapterNumber: 46, arc: 6 },
  { slug: 'chuong-47', title: 'Chương 47: Ta Sẽ Không Tha Thứ | I Won\'t Forgive', chapterNumber: 47, arc: 6 },
  { slug: 'chuong-48', title: 'Chương 48: Giết Người Trở Thành Thói Quen | Murder Becomes a Habit', chapterNumber: 48, arc: 6 },
  { slug: 'chuong-49', title: 'Chương 49: Gửi Người, Lời Bào Chữa Vô Giá Trị | To You, The Worthless Excuse', chapterNumber: 49, arc: 6 },
  { slug: 'chuong-50', title: 'Chương 50: Gửi Người, Lời Bào Chữa Tuyệt Đối Vô Giá Trị | To You, The Absolutely Worthless Excuse', chapterNumber: 50, arc: 6 },
  { slug: 'chuong-51', title: 'Chương 51: Tòa Tháp Của Người Sống (Phần 2) | Tower of The Living PART 2', chapterNumber: 51, arc: 6 },
  { slug: 'chuong-52', title: 'Chương 52: Xin Chúa Hãy Tha Thứ Cho Con | God, Please Forgive Me', chapterNumber: 52, arc: 6 },
  { slug: 'chuong-53', title: 'Chương 53: ーーMột Giọng Nói Vang Lên | ーーA Voice, Chimed', chapterNumber: 53, arc: 6 },
  { slug: 'chuong-54', title: 'Chương 54: Re: Bắt Đầu Lại Bản Thân Từ Con Số Không Ở Thế Giới Khác | Re: Starting Life in a Different World from Zero', chapterNumber: 54, arc: 6 },
  { slug: 'chuong-55', title: 'Chương 55: Gửi Người Đang Chờ Tuyết Tan | You Who Awaits The Snowmelt', chapterNumber: 55, arc: 6 },
  { slug: 'chuong-56', title: 'Chương 56: Bàn Về Những Gì Đang Chờ Đợi Phía Trước | Talking About What Awaits', chapterNumber: 56, arc: 6 },
  { slug: 'chuong-57', title: 'Chương 57: Tạm Thời Hãy Gác Nó Sang Một Bên | Let\'s Disregard It For Now', chapterNumber: 57, arc: 6 },
  { slug: 'chuong-58', title: 'Chương 58: Chuyện Nào Ra Chuyện Đó | That is That, This is This', chapterNumber: 58, arc: 6 },
  { slug: 'chuong-59', title: 'Chương 59: Thứ Mỉm Cười Trong Thế Giới Trắng Xóa | What Smiles in the White World', chapterNumber: 59, arc: 6 },
  { slug: 'chuong-60', title: 'Chương 60: Một Vệt Nắng Duy Nhất | A Single Spot of Sunshine', chapterNumber: 60, arc: 6 },
  { slug: 'chuong-61', title: 'Chương 61: ーーHãy Đứng Dậy | ーーStand Up', chapterNumber: 61, arc: 6 },
  { slug: 'chuong-62', title: 'Chương 62: Những Chấn Động Của Sự Sụp Đổ | Tremors of Collapse', chapterNumber: 62, arc: 6 },
  { slug: 'chuong-63', title: 'Chương 63: Năm Chướng Ngại | Five Obstacles', chapterNumber: 63, arc: 6 },
  { slug: 'chuong-64', title: 'Chương 64: Chướng Ngại Thứ Hai | The Second Obstacle', chapterNumber: 64, arc: 6 },
  { slug: 'chuong-65', title: 'Chương 65: Thứ Hai, Thứ Năm, Và Sau Đó | The Second, The Fifth, Followed By', chapterNumber: 65, arc: 6 },
  { slug: 'chuong-66', title: 'Chương 66: Cơ Hội Thứ Hai Tiến Tới Hồi Kết | A Second Chance For a Finale', chapterNumber: 66, arc: 6 },
  { slug: 'chuong-67', title: 'Chương 67: Tiểu Vương | Little King', chapterNumber: 67, arc: 6 },
  { slug: 'chuong-68', title: 'Chương 68: Người Phụ Nữ Của Chòm Thiên Yết | The Woman of Scorpius', chapterNumber: 68, arc: 6 },
  { slug: 'chuong-69', title: 'Chương 69: Thanh Thiết Chùy Phi Lý Của Kiếm | The Absurd Iron Hammer of the Sword', chapterNumber: 69, arc: 6 },
  { slug: 'chuong-70', title: 'Chương 70: Ngôi Sao Tha Thiết | The Earnest Star', chapterNumber: 70, arc: 6 },
  { slug: 'chuong-71', title: 'Chương 71: Đếm Một | Count One', chapterNumber: 71, arc: 6 },
  { slug: 'chuong-72', title: 'Chương 72: ■■ ■', chapterNumber: 72, arc: 6 },
  { slug: 'chuong-73', title: 'Chương 73: "Natsuki Subaru" | "Natsuki Subaru"', chapterNumber: 73, arc: 6 },
  { slug: 'chuong-74', title: 'Chương 74: Natsuki Subaru | Natsuki Subaru', chapterNumber: 74, arc: 6 },
  { slug: 'chuong-75', title: 'Chương 75: Louis Arneb | Louis Arneb', chapterNumber: 75, arc: 6 },
  { slug: 'chuong-76', title: 'Chương 76: Địa Ngục Mang Tên Bản Thân | The Hell Bearing the Name of Oneself', chapterNumber: 76, arc: 6 },
  { slug: 'chuong-77', title: 'Chương 77: Ngọn Lửa Phản Công | The Beacon of Counterattack', chapterNumber: 77, arc: 6 },
  { slug: 'chuong-78', title: 'Chương 78: Bốn Góc Bàn Cờ | Four Corners', chapterNumber: 78, arc: 6 },
  { slug: 'chuong-79', title: 'Chương 79: READY STEADY GO | READY STEADY GO', chapterNumber: 79, arc: 6 },
  { slug: 'chuong-80', title: 'Chương 80: Cái Chết Của Tâm Trí | Death of the Mind', chapterNumber: 80, arc: 6 },
  { slug: 'chuong-81', title: 'Chương 81: Rất Hân Hạnh Được Gặp Gỡ | Pleased to Meet You', chapterNumber: 81, arc: 6 },
  { slug: 'chuong-82', title: 'Chương 82: Xiềng Xích Song Hành Chiến Đấu | Shackle Accompanying Battle', chapterNumber: 82, arc: 6 },
  { slug: 'chuong-83', title: 'Chương 83: Ram | Ram', chapterNumber: 83, arc: 6 },
  { slug: 'chuong-84', title: 'Chương 84: Hò Ta Hò Ta! | Heave-Ho! Heave-Ho!', chapterNumber: 84, arc: 6 },
  { slug: 'chuong-85', title: 'Chương 85: Kẻ Thua Cuộc Đẹp Đẽ | Good Loser', chapterNumber: 85, arc: 6 },
  { slug: 'chuong-86', title: 'Chương 86: Trò Chuyện Về Ngày Hôm Qua | Conversing Of What Yesterday Held', chapterNumber: 86, arc: 6 },
  { slug: 'chuong-87', title: 'Chương 87: Sự Tôn Kính Phương Xa | Distant Regard', chapterNumber: 87, arc: 6 },
  { slug: 'chuong-88', title: 'Chương 88: Ta Hỏi Ý Chí Của Ngươi | I ask thy Will', chapterNumber: 88, arc: 6 },
  { slug: 'chuong-89', title: 'Chương 89: Shaula | Shaula', chapterNumber: 89, arc: 6 },
  { slug: 'chuong-90', title: 'Chương 90: Anh Hùng | Hero', chapterNumber: 90, arc: 6 },
  { slug: 'chuong-01', title: 'Chương 1: Lễ Rửa Tội | Baptism', chapterNumber: 1, arc: 7 },
  { slug: 'chuong-02', title: 'Chương 2: Lần Theo Dấu Vết Dã Thú | Animal Tracking', chapterNumber: 2, arc: 7 },
  { slug: 'chuong-03', title: 'Chương 3: Đối Đầu Với Rem | VS Rem', chapterNumber: 3, arc: 7 },
  { slug: 'chuong-04', title: 'Chương 4: Lựa Chọn Quả Cảm | A Brave Choice', chapterNumber: 4, arc: 7 },
  { slug: 'chuong-05', title: 'Chương 5: Làm Đàn Ông Thật Gian Nan | Being a Man is Tough', chapterNumber: 5, arc: 7 },
  { slug: 'chuong-06', title: 'Chương 6: Phương Nam Xa Xôi | A Land Faraway in the South', chapterNumber: 6, arc: 7 },
  { slug: 'chuong-07', title: 'Chương 7: Làm Đàn Ông Quả Thực Gian Nan | Being a Man was Tough', chapterNumber: 7, arc: 7 },
  { slug: 'chuong-08', title: 'Chương 8: Tên | Name', chapterNumber: 8, arc: 7 },
  { slug: 'chuong-09', title: 'Chương 9: Cách Sống Của Đế Quốc | The Way of the Empire', chapterNumber: 9, arc: 7 },
  { slug: 'chuong-10', title: 'Chương 10: Tộc Nhân Shudraq | The People of Shudraq', chapterNumber: 10, arc: 7 },
  { slug: 'chuong-11', title: 'Chương 11: Nghi Thức Huyết Tế | The Lifeblood Ritual', chapterNumber: 11, arc: 7 },
  { slug: 'chuong-12', title: 'Chương 12: Đế Quốc Vollachia | The Vollachian Empire', chapterNumber: 12, arc: 7 },
  { slug: 'chuong-13', title: 'Chương 13: Bản Chất Con Người | As a Mortal', chapterNumber: 13, arc: 7 },
  { slug: 'chuong-14', title: 'Chương 14: Giá Trị Bất Đồng | Unbridgeable Values', chapterNumber: 14, arc: 7 },
  { slug: 'chuong-15', title: 'Chương 15: Kẻ Tôi Muốn Bảo Vệ | Those I Want to Protect', chapterNumber: 15, arc: 7 },
  { slug: 'chuong-16', title: 'Chương 16: Tình Thế Đế Quốc | The Situation in the Empire', chapterNumber: 16, arc: 7 },
  { slug: 'chuong-17', title: 'Chương 17: Tai Họa Cận Kề | Looming Evil', chapterNumber: 17, arc: 7 },
  { slug: 'chuong-18', title: 'Chương 18: Trận Chiến Ở Thành Lũy Guaral | Battle in the Fortress City of Guaral', chapterNumber: 18, arc: 7 },
  { slug: 'chuong-19', title: 'Chương 19: Cuộc Ngộ Nhập Phiền Toái | A Vexing Reunion', chapterNumber: 19, arc: 7 },
  { slug: 'chuong-20', title: 'Chương 20: Hoàng Đế, Thương Nhân, Natsuki Subaru | Emperor / Merchant / Natsuki Subaru', chapterNumber: 20, arc: 7 },
  { slug: 'chuong-21', title: 'Chương 21: Zikr Osman | Zikr Osman', chapterNumber: 21, arc: 7 },
  { slug: 'chuong-22', title: 'Chương 22: Kế Hoạch Vây Thành Không Đổ Máu | The Bloodless Siege Plan', chapterNumber: 22, arc: 7 },
  { slug: 'chuong-23', title: 'Chương 23: Nhạc Công Natsumi Schwartz | Musician Natsumi Schwartz', chapterNumber: 23, arc: 7 },
  { slug: 'chuong-24', title: 'Chương 24: Kiêu Ngạo | Arrogance', chapterNumber: 24, arc: 7 },
  { slug: 'chuong-25', title: 'Chương 25: Cuộc Ngộ Phùng Như Huyết Lệ Thiêu Đốt | A Reunion Akin to Scorching Blood', chapterNumber: 25, arc: 7 },
  { slug: 'chuong-26', title: 'Chương 26: Hội Nghị Bàn Tròn Nhảy Múa | A Dancing Roundtable Conference', chapterNumber: 26, arc: 7 },
  { slug: 'chuong-27', title: 'Chương 27: Kẻ Sở Hữu Và Kẻ Tay Trắng | The Haves and the Have-Nots', chapterNumber: 27, arc: 7 },
  { slug: 'chuong-28', title: 'Chương 28: Điều Kiện Chiến Thắng | Victory Conditions', chapterNumber: 28, arc: 7 },
  { slug: 'chuong-29', title: 'Chương 29: Vị Thế Của Mỗi Người | To Each Their Stance', chapterNumber: 29, arc: 7 },
  { slug: 'chuong-30', title: 'Chương 30: Anh Hùng Tự Phong Natsuki Subaru | Self-Proclaimed Hero Natsuki Subaru', chapterNumber: 30, arc: 7 },
  { slug: 'chuong-31', title: 'Chương 31: Cuộc Trò Chuyện Giữa Những Người Đồng Hương | A Talk Between Compatriots', chapterNumber: 31, arc: 7 },
  { slug: 'chuong-32', title: 'Chương 32: Con Đường Phía Trước | The Path Onwards', chapterNumber: 32, arc: 7 },
  { slug: 'chuong-33', title: 'Chương 33: Giờ Thì, Lên Đường Tới Ma Đô | Now, Onto the Journey towards the Demon City', chapterNumber: 33, arc: 7 },
  { slug: 'chuong-34', title: 'Chương 34: Cãi Vã Trong Xe Ngựa | A Quarrel in the Carriage', chapterNumber: 34, arc: 7 },
  { slug: 'chuong-35', title: 'Chương 35: Đêm Trò Chuyện | A Night for Talking', chapterNumber: 35, arc: 7 },
  { slug: 'chuong-36', title: 'Chương 36: Ma Đô Hỗn Loạn | Chaotic Demon City', chapterNumber: 36, arc: 7 },
  { slug: 'chuong-37', title: 'Chương 37: Thành Chủ Hồng Ngọc Thành | The Lord of the Crimson Lapis Castle', chapterNumber: 37, arc: 7 },
  { slug: 'chuong-38', title: 'Chương 38: Phần Thưởng Tám Năm Chờ Đợi | A Reward Eight Years in the Making', chapterNumber: 38, arc: 7 },
  { slug: 'chuong-39', title: 'Chương 39: Ác Độc | Vicious', chapterNumber: 39, arc: 7 },
  { slug: 'chuong-40', title: 'Chương 40: Natchuki Subawu | Natchuki Subawu', chapterNumber: 40, arc: 7 },
  { slug: 'chuong-41', title: 'Chương 41: Trò Chuyện Bên Tách Trà | A Chat Over Tea', chapterNumber: 41, arc: 7 },
  { slug: 'chuong-42', title: 'Chương 42: Dã Thú Dã Tâm | Beast of Ambition', chapterNumber: 42, arc: 7 },
  { slug: 'chuong-43', title: 'Chương 43: Phía Sau Mí Mắt | Hidden Behind Your Eyelids', chapterNumber: 43, arc: 7 },
  { slug: 'chuong-44', title: 'Chương 44: Tầm Nhìn Thu Hẹp | Shrinking Vision', chapterNumber: 44, arc: 7 },
  { slug: 'chuong-45', title: 'Chương 45: Konkon | Konkon', chapterNumber: 45, arc: 7 },
  { slug: 'chuong-46', title: 'Chương 46: Sự Liều Lĩnh Trẻ Con | Childish Recklessness', chapterNumber: 46, arc: 7 },
  { slug: 'chuong-47', title: 'Chương 47: Bất Diệt ■■ | Unperishing ■■', chapterNumber: 47, arc: 7 },
  { slug: 'chuong-48', title: 'Chương 48: Mục Tiêu Ràng Buộc Nơi Ma Thành | Purposes Entangling in the Demon City', chapterNumber: 48, arc: 7 },
  { slug: 'chuong-49', title: 'Chương 49: Ngôi Sao Thẳng Hàng | The Stars Aligned', chapterNumber: 49, arc: 7 },
  { slug: 'chuong-50', title: 'Chương 50: Căn "Hầm" Có Tầm Nhìn Tuyệt Đẹp | A "Hole" With a Great View', chapterNumber: 50, arc: 7 },
  { slug: 'chuong-51', title: 'Chương 51: Nữ Chủ Ma Thành | The Demon City’s Mistress', chapterNumber: 51, arc: 7 },
  { slug: 'chuong-52', title: 'Chương 52: Tình Yêu Không Thể Chúc Thư | Love Can’t Be Bequeathed', chapterNumber: 52, arc: 7 },
  { slug: 'chuong-53', title: 'Chương 53: Điều Nằm Ngoài Giây Thứ Mười Một | What Lies Beyond the Eleventh Second', chapterNumber: 53, arc: 7 },
  { slug: 'chuong-54', title: 'Chương 54: Utopia của Chaosflame | The Utopia of Chaosflame', chapterNumber: 54, arc: 7 },
  { slug: 'chuong-55', title: 'Chương 55: Tiếng Huyên Náo Của Thành Phố Quỷ | The Cacophony of the Demon City', chapterNumber: 55, arc: 7 },
  { slug: 'chuong-56', title: 'Chương 56: Cuộc Đại Thảm Họa | The Great Disaster', chapterNumber: 56, arc: 7 },
  { slug: 'chuong-57', title: 'Chương 57: Không Thể Sống Khôn Ngoan Hơn | I Can’t Live Wiser', chapterNumber: 57, arc: 7 },
  { slug: 'chuong-58', title: 'Chương 58: Những Kẻ Không Nơi Nương Tựa | Those With No Place to Turn To', chapterNumber: 58, arc: 7 },
  { slug: 'chuong-59', title: 'Chương 59: Taritta Shudraq | Taritta Shudraq', chapterNumber: 59, arc: 7 },
  { slug: 'chuong-60', title: 'Chương 60: Gieo Mầm Hạt Giống Huyên Náo | The Planting of a Tumultuous Seedling', chapterNumber: 60, arc: 7 },
  { slug: 'chuong-54b', title: 'Chương 54B: Che Phủ Bầu Trời Xanh | Covering the Blue Sky', chapterNumber: 60.1, arc: 7 },
  { slug: 'chuong-55b', title: 'Chương 55B: Tiếng Huyên Náo Của Thành Lũy | The Cacophony of the Fortress City', chapterNumber: 60.2, arc: 7 },
  { slug: 'chuong-56b', title: 'Chương 56B: Tai Họa Phi Long | The Flying Dragon Cataclysm', chapterNumber: 60.3, arc: 7 },
  { slug: 'chuong-57b', title: 'Chương 57B: Bị Gọi Là Đồ Ngốc Cũng Chẳng Sao | I Don\'t Mind Being Called a Moron', chapterNumber: 60.4, arc: 7 },
  { slug: 'chuong-58b', title: 'Chương 58B: Những Kẻ Không Còn Nơi Để Quay Về | Those Who Have No Place to Turn To', chapterNumber: 60.5, arc: 7 },
  { slug: 'chuong-59b', title: 'Chương 59B: Flop O\'Connell | Flop O\'Connell', chapterNumber: 60.6, arc: 7 },
  { slug: 'chuong-61', title: 'Chương 61: Chào Mừng Đến Với Đảo Đấu Sĩ | Welcome, to the Gladiator Island!', chapterNumber: 61, arc: 7 },
  { slug: 'chuong-62', title: 'Chương 62: Luật Lệ Của Hòn Đảo | The Island’s Order', chapterNumber: 62, arc: 7 },
  { slug: 'chuong-63', title: 'Chương 63: Sparka | Sparka', chapterNumber: 63, arc: 7 },
  { slug: 'chuong-64', title: 'Chương 64: Những Từ Ngữ Ma Thuật | Magic Words', chapterNumber: 64, arc: 7 },
  { slug: 'chuong-65', title: 'Chương 65: Chiến Thần Ăn Chực Học Đường | The School Food Fighter', chapterNumber: 65, arc: 7 },
  { slug: 'chuong-66', title: 'Chương 66: Hiain Yatz | Hiain Yatz', chapterNumber: 66, arc: 7 },
  { slug: 'chuong-67', title: 'Chương 67: Ẩn Sau Chiếc Răng Hàm | Hidden Behind the Molar', chapterNumber: 67, arc: 7 },
  { slug: 'chuong-68', title: 'Chương 68: Sự Dẫn Dắt Của Kiếm Lang | Guidance of the Sword Wolf', chapterNumber: 68, arc: 7 },
  { slug: 'chuong-69', title: 'Chương 69: Đến Từ Đế Đô | Arriving from the Imperial Capital', chapterNumber: 69, arc: 7 },
  { slug: 'chuong-70', title: 'Chương 70: Một Điều Duy Nhất | One Thing', chapterNumber: 70, arc: 7 },
  { slug: 'chuong-71', title: 'Chương 71: Nước | Water', chapterNumber: 71, arc: 7 },
  { slug: 'chuong-72', title: 'Chương 72: ■■ ■', chapterNumber: 72, arc: 7 },
  { slug: 'chuong-73', title: 'Chương 73: Weitz Rogen | Weitz Rogen', chapterNumber: 73, arc: 7 },
  { slug: 'chuong-74', title: 'Chương 74: Idra Missanga | Idra Missanga', chapterNumber: 74, arc: 7 },
  { slug: 'chuong-75', title: 'Chương 75: Tôi Biết | I know', chapterNumber: 75, arc: 7 },
  { slug: 'chuong-76', title: 'Chương 76: Hội Ngộ Ngẫu Nhiên Nơi Đế Đô | Chance Meetings at the Imperial Capital', chapterNumber: 76, arc: 7 },
  { slug: 'chuong-77', title: 'Chương 77: Trò Đùa Của Số Phận | Twist of Fate', chapterNumber: 77, arc: 7 },
  { slug: 'chuong-78', title: 'Cuộc Tái Ngộ Đầy Biến Động | A Volatile Reunion', chapterNumber: 78, arc: 7 },
  { slug: 'chuong-79', title: 'Tiếng Cười Đỏ Thắm | A Roar of Scarlet Laughter', chapterNumber: 79, arc: 7 },
  { slug: 'chuong-80', title: 'Chương 80: Iris và Vua Gai | Iris and the King of Thorns', chapterNumber: 80, arc: 7 },
  { slug: 'chuong-81', title: 'Chương 81: Nữ Kiệt và Gã Hề | The Fierce Lady and the Clown', chapterNumber: 81, arc: 7 },
  { slug: 'chuong-82', title: 'Chương 82: Ý Đồ Phe Phiến Loạn | The Rebels’ Intent', chapterNumber: 82, arc: 7 },
  { slug: 'chuong-83', title: 'Chương 83: Chiến Loạn và Chiến Trường | Warfare and Warzones', chapterNumber: 83, arc: 7 },
  { slug: 'chuong-84', title: 'Chương 84: Tea chamber', chapterNumber: 84, arc: 7 },
  { slug: 'chuong-85', title: 'Chương 85: Người Bạn | Fhrend', chapterNumber: 85, arc: 7 },
  { slug: 'chuong-86', title: 'Chương 86: The Five Bastions | The Five Bastions', chapterNumber: 86, arc: 7 },
  { slug: 'chuong-87', title: 'Chương 87: Decisive Battle at the Bastion | Decisive Battle at the Bastion', chapterNumber: 87, arc: 7 },
  { slug: 'chuong-88', title: 'Chương 88: Làn Gió Mới | New Wind', chapterNumber: 88, arc: 7 },
  { slug: 'chuong-89', title: 'Chương 89: Kafma Irulux | Kafma Irulux', chapterNumber: 89, arc: 7 },
  { slug: 'chuong-90', title: 'Chương 90: Cái Nôi Địa Ngục | The Cradle of Hell', chapterNumber: 90, arc: 7 },
  { slug: 'chuong-91', title: 'Chương 91: Băng Qua Chiến Trường | Racing Across the Battlefield', chapterNumber: 91, arc: 7 },
  { slug: 'chuong-92', title: 'Chương 92: Nối Lại Tình Xưa | Rekindling Old Ties', chapterNumber: 92, arc: 7 },
]

export function getChaptersByArc(arc: number): ChapterMeta[] {
  return chapters
    .filter((c) => c.arc === arc)
    .sort((a, b) => a.chapterNumber - b.chapterNumber)
}

export function getChapterBySlug(
  arc: number,
  slug: string
): ChapterMeta | undefined {
  return chapters.find((c) => c.arc === arc && c.slug === slug)
}
