import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawPath = path.join(__dirname, 'translation_temp', 'arc7_ch60_raw.json');
const rawData = JSON.parse(fs.readFileSync(rawPath, 'utf-8'));

const translations = {
  161: "Khi các chức năng của Thành phố Quỷ bị mất, việc tìm nơi tiếp nhận những cư dân đang bơ vơ là điều cần thiết.",
  162: "Đề xuất của Abel là một việc cưỡng ép, vô lý khi bắt người khác phải chịu đựng những điều phi lý. Nhưng Yorna cũng có những ưu tiên tương tự. Cứu lấy những người mình yêu thương, đó mới chính là Yorna.",
  163: "Và ngoài chuyện đó ra――",
  164: "Yorna: [Ngài có chắc là thực sự sẵn sàng thực hiện nguyện ước của thiếp trong mật thư chứ?]",
  165: "Abel: [Ta không có ý định nói lại lần thứ hai. Tuy nhiên, ngươi phải suy nghĩ kỹ về chuyện đó.]",
  166: "Yorna: [Suy nghĩ kỹ sao…]",
  167: "Abel: [Ngươi ưu tiên điều gì hơn, nguyện ước bấy lâu nay hay \"tình yêu\" của chính mình?]",
  168: "Với một Abel không để lộ chút cảm xúc nào, Yorna không thể biết được những lời nói đó, hay đúng hơn là lời khuyên của hắn, là thiện chí hay ác ý.",
  169: "Nhưng Yorna, bị đánh trúng tâm lý bởi những lời nói đó, rút tẩu thuốc kiseru từ thắt lưng ra, dùng ngón tay chỉnh lại đầu tẩu bị vẹo, châm lửa rồi để làn khói tím tỏa ra.",
  170: "Phía dưới, những người thân yêu của Yorna đang tìm kiếm khắp thành phố đổ nát, gom góp cuộc sống của họ, những thứ giúp họ duy trì sự sống, chuẩn bị cho những gì tiếp theo.",
  171: "Trách nhiệm của Yorna là che chở cho họ, và là tia sáng dẫn lối cho họ hướng tới ngày mai.",
  172: "Tin tưởng Abel, kéo Vincent Vollachia―― không, kẻ giả mạo hắn xuống khỏi ngai vàng, và bắt hắn phải thực hiện lời hứa trong mật thư.",
  173: "Và về nội dung những lời hứa cần được thực hiện――",
  174: "Yorna: [――Chẳng phải cha mẹ nên là người ra đi trước sao, Tanza?]",
  175: "Và cứ thế, đứa trẻ yêu quý đã tự quyết định vận mệnh của mình biến mất, tựa như làn khói tím trong cơn gió thoảng qua.",
  176: "△▼△▼△▼△",
  177: "Khi quan sát làn khói tím bốc lên từ đằng xa, cô chào người đàn ông đeo mặt nạ quỷ khi hắn bước ra từ phía dưới ngọn đồi đó.",
  178: "Kẻ được đón tiếp, Abel, khẽ hừ một tiếng trước cảnh tượng Taritta đứng chôn chân tại đó,",
  179: "Abel: [Nếu ngươi đang lo lắng về cái chân bị bắn thủng thì đó chỉ là sự lo lắng thừa thãi. Vết thương đã bắt đầu lành rồi. Ngày mai nó sẽ bình phục hoàn toàn.]",
  180: "Taritta: […Tôi mừng vì điều đó. Nhưng đó không phải là điều tôi lo lắng.]",
  181: "Abel: [Ồ?]",
  182: "Đúng như Abel đã nói, không thấy chút khó chịu nào về mặt thể xác trên phong thái của Yorna khi cô đứng trên đồi. Bộ kimono và mái tóc bù xù của cô, nhìn từ phía sau, toát lên vẻ kiệt sức, nhưng cái chân phải bị trúng tên lại tỏa ra một luồng khí khác.",
  183: "Bản thân điều đó có lẽ là nhờ vào bí thuật mà cô thao túng. Tuy nhiên, hậu quả của việc gây ra vết thương còn nặng nề hơn bản thân vết thương đó.",
  184: "Dĩ nhiên, Taritta hiểu rõ sức nặng đó.",
  185: "Taritta: [――――]",
  186: "Vào thời khắc cuối cùng đó, khi được giao phó một lựa chọn, bản thân Taritta đã phó mặc quyết định cho một mũi tên.",
  187: "Nếu tuân theo mệnh lệnh của Mariuli với tư cách là một Stargazer, Taritta đã bắn xuyên tim Abel bằng mũi tên đó. Đúng là đây là khả năng hứa hẹn nhất trong các lựa chọn của Taritta, mặc dù khó có thể tưởng tượng được mối quan hệ nhân quả nào sẽ dẫn đến việc dập tắt Great Disaster.",
  188: "Nhưng xét đến việc Mariuli, người mà cô vô cùng yêu quý, đã biến thành một thực thể xa lạ, chỉ biết tuân theo các vì sao, thì quyết định đó cũng không khác gì việc tự cắt ngắn mạng sống của chính mình.",
  189: "――Đến tận cuối cùng, đó chính là điểm mấu chốt khiến Taritta đưa ra quyết định đó.",
  190: "Taritta căm ghét các vì sao đã thay đổi Mariuli. Vì vậy, cô không đi theo các vì sao.",
  191: "Có lẽ việc chỉ tuân theo mệnh lệnh sẽ phù hợp với tính cách của Taritta, một người quen với việc được bảo phải làm gì, được chỉ đường, và sẵn sàng tuân theo lệnh của người khác.",
  192: "Tuy nhiên, cuộc gặp gỡ giữa Taritta và các vì sao lại là một cuộc gặp gỡ tồi tệ.",
  193: "Nếu các vì sao nói chuyện với Taritta ngay từ đầu thay vì Mariuli, Taritta có lẽ đã sống vì các vì sao. Nhưng chuyện đó đã không xảy ra.",
  194: "Vì thế――",
  195: "Taritta: [――Vào khoảnh khắc đó, tôi đã đẩy lưng cô bé á nhân hươu đó khi cô bé chạy đi mà không hề do dự.]",
  196: "Kết quả là, cô bé bằng cách nào đó đã tạo ra ánh sáng tiêu diệt Great Disaster từ bên trong.",
  197: "Đổi lại, mạng sống của cô bé biến mất, và mức độ tàn phá đối với vùng đất nơi Thành phố Quỷ từng tọa lạc là không hề nhỏ. Tuy nhiên, có thể tuyên bố rằng cô bé đã bảo vệ được những gì mình muốn bảo vệ.",
  198: "Abel: [Thế nhưng bất chấp điều đó, trông ngươi chẳng có vẻ gì là vui mừng cả.]",
  199: "Taritta: […Tôi đã đúng, phải không? Khi không tuân theo mệnh lệnh, và không bắn ngài.]",
  200: "Abel: [Làm như ta, kẻ không bị bắn, sẽ nói với ngươi rằng ngươi nên nổ súng vậy. Quyết định của ngươi đúng hay sai cũng không nằm trong phạm vi những điều ta nên nói. Nghe có vẻ sáo rỗng, nhưng sự đúng đắn trong lựa chọn của ngươi chỉ có thể được chứng minh bằng hành động của ngươi sau này thôi.]",
  201: "Taritta: […Những lời đó, tôi không nghĩ chúng thuộc về ngài.]",
  202: "Abel: [Chính xác. Từ \"Iris và Vua Gai\"… Một câu trích từ một tác phẩm kinh điển.]",
  203: "Nói về một vấn đề mà Taritta không hiểu, Abel lắc đầu nói \"Ngươi không cần hiểu\".",
  204: "Hắn sau đó nhìn Taritta từ đầu đến chân,",
  205: "Abel: [Ngươi có lẽ vẫn còn chút lo sợ ngay cả lúc này, nhưng có vẻ ngươi đã vượt qua được phần nào rồi. Giờ thì, ngươi sẽ làm gì?]",
  206: "Taritta: [Tôi cũng không biết chắc. Tôi chỉ muốn quay lại thành phố đó và trò chuyện với chị gái cùng bộ tộc của mình. Tôi muốn nói chuyện với đứa con gái của người chị tri kỷ đã khuất của tôi.]",
  207: "Abel: [Một người chị tri kỷ đã để lại mệnh lệnh cho ngươi sao… Việc làm sáng tỏ lý do tại sao bản thân ngươi không phải là một Stargazer giờ đây đã có lý rồi. Một lũ ngày càng đáng ghê tởm.]",
  208: "Taritta: [Đáng ghê tởm…]",
  209: "Abel: [Ta không nói về ngươi. Ta hiểu kế hoạch chung của ngươi rồi.]",
  210: "Abel quay đầu lại trước những lời lẩm bẩm của Taritta.",
  211: "Một lượng lớn người đang tiến vào những con phố đã thành đống đổ nát, thu lượm những đồ dùng gia đình thoát khỏi sự tàn phá, cũng như những vật liệu có thể sử dụng cho mục đích nào đó, và bắt đầu ưu tiên những gì cần thiết để duy trì sự sống.",
  212: "Taritta bị ấn tượng bởi khả năng phục hồi trong lối sống của những người từ Thành phố Quỷ.",
  213: "Nhớ lại nguồn gốc của Thành phố Quỷ, họ có lẽ đã quen với việc bị ngược đãi, áp bức và thất bại. Ngay cả khi tính đến chuyện đó thì vẫn vậy.",
  214: "Vì thế――",
  215: "Taritta: [Những người đó, ngài định kéo họ vào cuộc chiến của mình sao?]",
  216: "Abel: [Chính xác.]",
  217: "Bất giác, Taritta cảm thấy nản lòng trước câu trả lời ngắn gọn, dứt khoát đó.",
  218: "Không hề do dự; Abel quan sát những người đang cố gắng hết sức trên vùng đất bị tàn phá, nhưng vẫn nhất quán với mục đích ban đầu khi đến Chaosflame, dậm gót chân phát ra tiếng động.",
  219: "Và rồi――",
  220: "Al: [――Mặc dù ý kiến của Abel-chan có thể đúng, nhưng tôi tự hỏi liệu những người xung quanh hắn có chịu nghe lời một cách lặng lẽ như vậy không. Ngay cả người đẹp cáo cũng có thể khó đứng về phía chúng ta về mặt cảm xúc, đúng không?]",
  221: "Trong khi bày tỏ một ý kiến hợp lý, Al tham gia cùng Abel và Taritta.",
  222: "Gã đã khuất tầm mắt một thời gian, nhưng đánh giá từ cách gã đội lại chiếc mũ giáp quen thuộc lên đầu và uể oải bước đi về phía họ, có vẻ như một thứ gì đó ngoài kích thước bình thường của gã đã được khôi phục.",
  223: "Bên cạnh Al là Medium, cô bé ngước nhìn Abel với đôi mắt xanh tròn xoe,",
  224: "Medium: [Tôi cũng cảm thấy như Al-chin vậy nha. Tôi sẽ rất vui nếu Yorna-chan đứng về phía chúng ta, nhưng sau những gì xảy ra với Tanza-chan và thành phố, tôi không chắc cô ấy muốn tham gia vào chuyện này…]",
  225: "Abel: [Ngươi đang muốn nói rằng Yorna Mishigure sẽ không đi theo chúng ta, những kẻ đã mang theo thực thể ở trung tâm thảm họa sao? Ý nghĩ đó quá ủy mị rồi. Cô ta đã đưa ra quyết định của mình.]",
  226: "Medium: [Thật sao nha? Abel-chin, ngài không lại nói gì đó quá đáng với cô ấy nữa chứ nha?]",
  227: "Abel: [Bất kể họ có nhẫn tâm đến mức nào, ta sẽ nói những gì cần phải làm. Ý định của ta rất rõ ràng.]",
  228: "Đôi má của Medium phồng lên trước sự từ chối phủ nhận câu hỏi cô bé đặt ra của Abel.",
  229: "Thực tế, từ những gì lọt vào tai Taritta, cuộc đối thoại giữa Abel và Yorna không hề mang tính cảm xúc, nhưng nó còn lâu mới được coi là dịu dàng, bình tĩnh và thân mật.",
  230: "Dẫu vậy, lý do Abel không nghi ngờ ý định của Yorna là vì,",
  231: "Al: [Anh sẵn sàng tận dụng điểm yếu của cô Yorna… Sau cùng, nếu cô ấy không đi chung đường với chúng ta, cô ấy không thể bảo vệ những cư dân thành phố không còn nơi nào khác để đi, phải không?]",
  232: "Medium: [Trời đất ơi…! Lại là những lời nhẫn tâm của ngài nữa rồi, Abel-chin.]",
  233: "Abel: [Họ còn lựa chọn nào khác sao? Lựa chọn duy nhất còn lại cho họ là bám lấy sự bướng bỉnh vô nghĩa của mình và chết như một con chó.]",
  234: "Medium: [Không còn cách nào khác, nhưng vẫn còn cách nói khác mà! Tại sao ngài không hiểu chuyện đó chứ nha!]",
  235: "Abel ném một cái nhìn lạnh lùng về phía Medium qua chiếc mặt nạ quỷ của mình, cô bé gặng hỏi câu trả lời bằng cách cao giọng.",
  236: "Taritta tin chắc Abel sẽ đưa ra một phán quyết tàn nhẫn đối với những lời phàn nàn của Medium, nhưng cảm xúc của cô lại gần với Medium hơn.",
  237: "Tuy nhiên, miễn là tuân theo Khế ước giữa Hoàng đế đời trước và Tộc nhân Shudraq, Taritta không thể bỏ rơi Abel và cắt đứt mối quan hệ của họ.",
  238: "Mấy thứ như đồng minh về mặt tình cảm không có ý nghĩa gì trên một chiến trường thực tế.",
  239: "Al: [Cô nhóc Medium tức giận là phải. Tuy nhiên, cá nhân tôi không ghét ý tưởng tận dụng bất cứ thứ gì có thể của Abel. Tôi sẽ không có ý kiến gì nếu cô Yorna đi cùng chúng ta chỉ vì mục đích thực dụng.]",
  240: "Medium: [Tôi đang nói là tôi có rất nhiều ý kiến phản đối chuyện đó nha. Tôi cũng ghét anh luôn, Al-chin!]",
  241: "Al: [Nghe cô nhóc Medium ghét tôi làm tôi đau lòng quá đấy. Dù sao thì…]",
  242: "Cắt ngang câu nói của mình ở đó, trong khi giữ chân Medium, người đang lườm cả Abel và gã, Al đảo mắt xung quanh, hướng sự chú ý về phía cái hố lớn ở trung tâm khu vực bị phá hủy.",
  243: "Khi hành động đó thu hút sự chú ý của Taritta và những người khác, và cũng hướng về phía đó, gã cất lời,",
  244: "Al: [Hãy nói về người của chúng ta đi.――Về cộng sự.]",
  245: "Mọi người: [――――]",
  246: "Khi Al khơi gợi chủ đề này, bầu không khí khô khốc trở nên căng thẳng hơn một chút.",
  247: "Đó là một chủ đề mà tất cả họ đều biết phải bàn tới, nhưng đồng thời, đó cũng là chủ đề khiến họ cảm thấy hơi khó xử, tự hỏi không biết nên nói gì.",
  248: "Dù thế nào đi nữa――",
  249: "Medium: [Subaru-chin, anh đã đi đâu rồi chứ nha…?]",
  250: "Lời lẩm bẩm u sầu của Medium nói về một tổn thất có quy mô nhỏ hơn do Great Disaster gây ra.",
  251: "So với thực tế là một trong những thành phố lớn nhất mà Đế quốc tự hào đã biến mất hoàn toàn, và thực tế là tính mạng của hai vị Hoàng đế đã gặp nguy hiểm, tổn thất đó có lẽ có thể được coi là khá nhỏ nhặt.",
  252: "Tuy nhiên, đối với nhóm người đến Thành phố Quỷ, đó là tổn thất không thể bỏ qua.",
  253: "Medium: [Yorna-chan nói rằng những bóng đen tràn ra từ Subaru-chin nha.]",
  254: "Al: [Lão già Olbart cũng nói vậy. Lão cười tươi rói ngay cả khi bàn tay phải của mình đã biến mất. Với tư cách là một kẻ có thâm niên một tay, thật không thể tin nổi.]",
  255: "Taritta: [Ý ngài là thái độ của lão già đó sao? Hay là những gì lão nói?]",
  256: "Al: [Bực thật đấy, nhưng ở đây là thái độ. Còn về những gì lão nói, tôi chắc chắn đó là sự thật.]",
  257: "Tặc lưỡi một cái, Al nói rằng gã tin vào lời khai của Olbart.",
  258: "Taritta cũng không có ấn tượng tốt về lão già quái dị đó, nhưng sự thật là lão không có lý do gì để nói dối. Miễn là những gì lão tuyên bố trùng khớp với những gì Yorna nói, thì đó có lẽ là sự thật.",
  259: "Đột nhiên, điều xuất hiện trong tâm trí Taritta là ký ức về di chúc của Mariuli, \"Một lữ khách, có mái tóc đen, và đôi mắt đen\".",
  260: "Khi lần đầu tiên nhìn thấy Subaru trong rừng và nhắm vào mạng sống của cậu, trong đầu cô không hề có chút nghi ngờ nào về cậu. Sau đó, khi biết được sự tồn tại và danh tính của Abel, việc hắn bị mắc bẫy trong làng, cô tin chắc mình đã đánh giá sai đối thủ, nhưng――",
  261: "Taritta: [Liệu có khi nào…]",
  262: "Liệu có khi nào chính Subaru, chứ không phải Abel, mới là kẻ chịu trách nhiệm cho Great Disaster mà Mariuli dự đoán với tư cách là một Stargazer?",
  263: "Đó có thể là lý do tại sao Great Disaster lại tràn ngập với Subaru là tâm điểm.",
  264: "Những nghi ngờ như vậy cứ bám lấy trái tim Taritta.",
  265: "Abel: [Có một chuyện chúng ta phải thống nhất quan điểm.]",
  266: "Nỗi dằn vặt của Taritta bị gác lại khi Abel giơ một ngón tay lên trước mặt cả nhóm.",
  267: "Sau khi thu hút sự chú ý của họ, Abel lần lượt quan sát gương mặt của Medium, Al và Taritta, rồi tuyên bố,",
  268: "Abel: [Nhìn cách các ngươi nói chuyện, có vẻ như sự sống sót của thứ đó… của Natsuki Subaru là điều các ngươi không hề nghi ngờ. Các ngươi thực sự tin rằng cậu ta đã sống sót sau cảnh tượng tồi tệ đó sao?]",
  269: "Medium: [――Hự, dĩ nhiên rồi nha! Chuyện anh ấy chết là…]",
  270: "Abel: [Đừng nói mấy câu như không muốn nghĩ về chuyện đó. Dù có khó chấp nhận đến mấy, những chuyện gì phải xảy ra thì sẽ xảy ra. Sự sống chết của con người vốn rất mong manh.]",
  271: "Medium: [Abel-chin…]",
  272: "Tông giọng thực tế của Abel va chạm trực diện với sự khăng khăng mang tính cảm xúc của Medium.",
  273: "Về phần Taritta, tình cảm của cô lúc này cũng nghiêng về phía Medium. Nhưng cô không hy vọng Subaru có thể sống sót, vì cậu là tâm điểm của thảm họa này.",
  274: "Có lẽ, đó là vì cuộc sống hàng ngày của cô dành cho việc săn bắn, tiếp xúc với sự sống và cái chết của các sinh vật.",
  275: "Tộc nhân Shudraq là những chiến binh dũng cảm, nhưng ngay cả những cuộc đi săn thường ngày cũng rất nguy hiểm. Đôi khi, dã thú sẽ chống trả trong cơn giãy giụa trước khi chết, và những người bạn đồng hành của cô sẽ mất mạng.",
  276: "Con người chết đi. Rất dễ dàng. Dù cho người đó có quan trọng hay không cũng chẳng có gì khác biệt.",
  277: "Taritta: [Rất tiếc, nhưng Subaru…]",
  278: "Al: [Bro còn sống.]",
  279: "Medium: [――Al-chin!]",
  280: "Lắc đầu, Taritta cố gắng bày tỏ lời chia buồn. Nhưng câu nói của cô bị ngắt quãng bởi những lời đầy tin tưởng của Al; nghe thấy chúng khiến gương mặt Medium bừng sáng.",
  281: "Lẽ tự nhiên, Abel hướng đôi mắt có vẻ khó chịu về phía Al,",
  282: "Abel: [Tên hề kia, sao ngươi có thể chắc chắn về sự sống sót của cậu ta như vậy?]",
  283: "Al: [Đơn giản thôi, vì Natsuki Subaru là kiểu người như thế. Hay nói đúng hơn là…]",
  284: "Abel: [Đúng hơn là?]",
  285: "Al: [Thế giới vẫn chưa bị hủy diệt. Đó là cơ sở của tôi.]",
  286: "Taritta không thể hoàn toàn tiếp thu lý do và logic mà Al đưa ra. Có vẻ như Medium cũng vậy, cô bé cũng nghiêng đầu với vẻ mặt không hiểu chuyện gì.",
  287: "Abel cũng vậy, hắn gạt phắt đi ngay lập tức, bảo gã \"Bớt nói mấy lời ngu ngốc lại đi\",",
  288: "Abel: [Ta không có thời gian rảnh rỗi để nghe lời vô lý của ngươi. Nếu ngươi muốn làm một tên hề, hãy làm chuyện đó quanh Priscilla đi.]",
  289: "Al: [Tôi cũng muốn làm thế lắm, nhưng tiếc là Công chúa không có ở đây. Tiện nói về sự thật đáng tiếc đó, tôi cũng muốn hỏi anh điều tương tự đấy, Abel-chan.]",
  290: "Abel: [Chuyện gì.]",
  291: "Al: [Anh nghĩ sao, Abel-chan? Anh có tin bro đã chết không?]",
  292: "Chạm vào cằm chiếc mũ giáp của mình, Al hỏi Abel về suy nghĩ của đối phương. Tuy nhiên, ý kiến của hắn có vẻ đã rõ ràng. Hắn là người đã khơi mào cuộc chất vấn bằng một tông giọng như thế, nghi ngờ sự tỉnh táo của họ khi tin rằng Subaru vẫn còn sống.",
  293: "Lẽ tự nhiên, đối với hắn, niềm tin rằng Subaru, kẻ đã ở trong Great Disaster, đã sống sót――",
  294: "Abel: [――Vì đó không phải là Great Disaster, nên vai trò của cậu ta vẫn còn. Nếu cậu ta sở hữu năng lực cho mục đích đó, thì vẫn còn quá sớm để cho rằng cậu ta đã chết.]",
  295: "Taritta: [Hả…]",
  296: "Medium: [Abel-chin!?]",
  297: "Nhưng những gì Abel thực sự tuyên bố lại trái ngược với những gì Taritta mong đợi.",
  298: "Câu trả lời khiến Taritta không nói nên lời, và ngay cả Medium, người đáng lẽ đã có được câu trả lời mình tìm kiếm, cũng tròn mắt ngạc nhiên.",
  299: "Tuy nhiên, Abel không thèm nhìn Taritta và những người khác, hắn lập tức quay người bỏ đi, rồi chậm rãi bước ra khỏi nơi đó.",
  300: "Nhìn nhau, Taritta và Medium sau đó đi theo hắn. Al cũng đi theo sau lưng ba người họ, nghiêng đầu bối rối."
};

for (const item of rawData) {
  if (translations[item.id] !== undefined) {
    item.vi = translations[item.id];
  }
}

const partPath = path.join(__dirname, 'translation_temp', 'ch60_part2.json');
fs.writeFileSync(partPath, JSON.stringify(rawData.filter(x => x.id > 160 && x.id <= 300), null, 2), 'utf-8');
console.log("Saved part 2 to", partPath);
