import fs from 'fs'
import path from 'path'

function unescapeXml(str) {
  return str
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
}

const chapters = [87, 88, 89, 90]

for (const ch of chapters) {
  const filePath = path.join(process.cwd(), 'content', 'arc6', `chuong-${ch}.mdx`)
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`)
    continue
  }
  
  const content = fs.readFileSync(filePath, 'utf-8')
  
  // Extract all <Sentence en="...">...</Sentence>
  // Note: en attribute can span multiple lines or contain escaped quotes.
  // A robust way since we know it's generated by compile_mdx is to find <Sentence en="...
  const sentences = []
  const matches = content.matchAll(/<Sentence en="([\s\S]*?)">/g)
  for (const match of matches) {
    const rawEn = match[1]
    sentences.push(unescapeXml(rawEn))
  }
  
  const outPath = path.join(process.cwd(), 'scripts', `ch${ch}_extracted.json`)
  fs.writeFileSync(outPath, JSON.stringify(sentences, null, 2), 'utf-8')
  console.log(`Extracted ${sentences.length} sentences from Chapter ${ch} to ${outPath}`)
}
