import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawPath = path.join(__dirname, 'translation_temp', 'arc7_ch60_raw.json');
const rawData = JSON.parse(fs.readFileSync(rawPath, 'utf-8'));

const translations = {
  1: "△▼△▼△▼△",
  2: "Dịch máy bởi:",
  3: "Hiệu đính bởi:",
  4: "Kiểm dịch Nhật-Anh bởi:",
  5: "Nguồn ảnh:",
  6: "※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※",
  7: "Đây là bản dịch máy đã qua biên tập, được kiểm chứng chất lượng bởi nhất một dịch giả Nhật-Anh. Bản dịch này có thể có sai sót nhỏ về độ chính xác, do đó độc giả nên cân nhắc sự đánh đổi giữa tốc độ cập nhật và chất lượng bản dịch. Bản dịch chất lượng cao hơn cho chương này đang được đội ngũ thực hiện, nếu muốn bạn có thể chờ đợi thêm một thời gian và theo dõi cập nhật trên trang truyền thông xã hội của chúng tôi.",
  8: "※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※",
  9: "Vincent: [――Yorna Mishigure phải từ bỏ Thành phố Quỷ để cố gắng tiêu diệt Great Disaster. Soul Marriage Technique có thể thành công trong việc này, nhưng không có gì bảo đảm.]",
  10: "Tanza: […Giả sử dâng nộp Thành phố Quỷ mà vẫn không đủ…]",
  11: "Vincent: [Nếu chuyện đó xảy ra, Great Disaster, không còn cách nào ngăn chặn, sẽ đe dọa nuốt chửng toàn bộ Đế quốc, hoặc thậm chí xa hơn thế, lan rộng ra ngoài biên giới. Với Thành phố Quỷ là tâm chấn.]",
  12: "Tanza: [――――]",
  13: "Vincent: [――――]",
  14: "Tanza: [Yorna-sama sẽ không chấp thuận từ bỏ thành phố này.]",
  15: "Vincent: [Đây không phải lúc để ủy mị. Dù có muốn hay không, thành phố này vẫn sẽ bị bỏ hoang. Ngay từ đầu, việc thuyết phục cô ta không thuộc về trách nhiệm của ta.]",
  16: "Tanza: [Ngài tin cậu ta có thể thuyết phục được Yorna-sama?]",
  17: "Vincent: [Nếu không thể, tất cả sẽ tan thành tro bụi. Nếu buộc phải làm, cậu ta sẽ thực hiện. Cậu ta chính là kiểu người như vậy, xưa nay luôn duy trì cách sống đó.]",
  18: "Tanza: […Tôi không hiểu. Nếu ngài biết nhiều và chắc chắn về cậu ta như vậy, ngài còn muốn gì ở tôi?]",
  19: "Vincent: [Ngươi chắc cũng tự hiểu ý đồ của ta. Ngươi tuy còn nhỏ tuổi, nhưng lại ở vị trí có thể được kẻ trị vì Thành phố Quỷ trọng dụng rất nhiều.]",
  20: "Tanza: [――――]",
  21: "Vincent: [Trong trường hợp Great Disaster không bị tiêu diệt, Yorna Mishigure sẽ phải gánh chịu đau khổ tột cùng. Thành phố Quỷ sẽ được dùng để chống lại Great Disaster chưa phát triển hoàn chỉnh, nhưng nếu điều đó vẫn chưa đủ――]",
  22: "Tanza: [――Tôi…]",
  23: "Vincent: [――――]",
  24: "Tanza: [Yorna-sama… Vì lợi ích của Yorna Mishigure vĩ đại nhất, một phu nhân tựa như người mẹ nhân từ, tôi sẵn sàng tử vì đạo vì tình yêu xa xôi ấy, tôi đoán vậy.]",
  25: "Vincent: [――. Đó là một nghĩa cử cao đẹp.]",
  26: "Tanza: [Tôi không cần lời an ủi hay ca tụng. ――Ngoại trừ giọt lệ của Yorna-sama.]",
  27: "△▼△▼△▼△",
  28: "Yorna: [――Đừng!]",
  29: "Tanza chạy đi khi giọng nói của Yorna vang lên phía sau, phu nhân vươn tay ra, hét lên với vẻ mặt đầy đau đớn.",
  30: "Lao mình về phía trước, Tanza thoăn thoắt dậm chân lên mặt đất, con mắt bên phải rực cháy sắc đỏ, cơ thể nhỏ nhắn tràn đầy sức mạnh mà ngay cả những Binh lính Đế quốc giáp trụ đầy mình cũng không thể bì kịp.",
  31: "Cô bé không phải là một chiến binh xuất chúng, cũng chẳng giỏi ma pháp hay những bí thuật đặc biệt.",
  32: "Dù vậy, vào lúc này không ai có thể ngăn cản nổi cô bé.",
  33: "Lý do là bởi cô bé biết mình được Yorna yêu thương, được yêu thương nhiều hơn bất kỳ ai khác.",
  34: "Cô bé ở bên cạnh hỗ trợ Yorna, được phu nhân trao gửi tình thương, trò chuyện, giúp đỡ, quan tâm, và cầu nguyện cho.",
  35: "Yêu thương Yorna, và được Yorna yêu thương, chính là những điều kiện cần thiết để nhận được lợi ích tối đa từ Soul Marriage Technique―― thế nhưng tình yêu Tanza dành cho Yorna không hề xuất phát từ tư lợi.",
  36: "Có kẻ nói với vẻ thông thái rằng tình yêu chân chính không cần hồi báo.",
  37: "Nhưng Tanza tin vào điều đó. ――Cô bé tin rằng cảm xúc yêu thương một ai đó bản thân nó đã là một phần thưởng.",
  38: "Nghĩ về người đó và nhịp đập con tim của họ chính là phần thưởng của tình yêu.",
  39: "Vì thế Tanza phải đáp lại điều đó, bằng toàn bộ cơ thể nhỏ bé của mình, để đền đáp những gì đã nhận được.",
  40: "Đó chính là――",
  41: "Tanza: [Lý do tôi được ban tặng sinh mệnh này.]",
  42: "Lần đầu tiên Tanza được diện kiến Yorna sau khi bị xua đuổi khỏi nơi khác, cô bé còn quá nhỏ. Nép mình sau lưng người chị gái dịu dàng, cô bé chẳng thể làm gì ngoài ngước nhìn Yorna và phong thái uy nghiêm của phu nhân.",
  43: "Nhưng, lần đầu tiên trong đời, cô bé được hứa hẹn rằng mình có thể sống những ngày tháng mà không bị bất kỳ ai đe dọa. Tin tưởng vào lời hứa đó, cô bé đã có những suy nghĩ thoáng qua về việc trải qua những ngày tháng yên bình bên chị gái.",
  44: "Lần thứ hai diện kiến Yorna, sau khi người chị bị cướp đi bởi những thứ kinh hoàng, Tanza đã gào thét vào mặt Yorna trong tuyệt vọng; tuy nhiên, Yorna không hề trách phạt cô bé.",
  45: "Ngược lại, phu nhân chân thành lắng nghe lời cầu xin của Tanza và thậm chí còn giúp báo thù cho người chị đã khuất. ――Dù cho đổi lại, phu nhân sẽ bị mang danh là kẻ phản nghịch.",
  46: "Tại sao cô bé lại không yêu thương phu nhân cho được?",
  47: "Một người nhân từ, đã trao cho Tanza biết bao tình yêu thương và lòng trắc ẩn từ trước tới nay.",
  48: "Phu nhân đã khóc trước cái chết của chị gái Tanza, hối tiếc vì không thể giữ lời hứa, và xin lỗi cô bé.",
  49: "――Tại sao cô bé lại không yêu thương phu nhân cho được?",
  50: "Tanza: [――――]",
  51: "Trước mặt cô bé, một khối đen ngòm ngọ nguậy đầy uế khí đang tụ lại sau làn khói bụi mù mịt.",
  52: "Thành phố mà Yorna yêu quý đã bị hủy diệt, song ý chí kiên định của phu nhân vẫn chưa hề lay chuyển. Tanza không hề sợ hãi trước bóng tối khiến bất kỳ ai cũng muốn lánh mắt đi kia.",
  53: "Nếu nỗi sợ là lý do để chùn bước, thì đó không phải là thứ ngự trị trong trái tim Tanza.",
  54: "Theo đó, Tanza dậm chân nhảy lên các mảnh vụn, lao thẳng vào Great Disaster đang chập chờn trước mắt.",
  55: "Nếu quay đầu lại, nó sẽ trở thành nỗi vương vấn. Cô bé biết điều đó sẽ biến thành một lời nguyền.",
  56: "Nhưng――",
  57: "Yorna: [Tanza――!]",
  58: "Nghe thấy người mình yêu quý gọi tên, Tanza ngoảnh đầu lại phía sau.",
  59: "Ở đó, cô bé nhìn thấy Yorna đang ngã trên mặt đất, vươn tay về phía mình. Một mũi tên đã găm sâu vào chân phu nhân đầy đau đớn; cô bé hiểu rằng kẻ cầm cung từ đằng xa chính là người đã làm việc đó.",
  60: "Nếu không có mũi tên ấy, Yorna chắc chắn đã lao thẳng vào Great Disaster, lao về phía Tanza.",
  61: "Tanza thầm biết ơn người bắn tên, bởi bản thân cô bé không thể làm điều gì quyết liệt như thế.",
  62: "Và rồi――",
  63: "Tanza: [――Yorna-sama.]",
  64: "Đôi môi cô bé mấp máy.",
  65: "Liệu những lời tiếp theo có truyền đến tai Yorna hay không, cô bé không rõ.",
  66: "Thế nhưng, vào khoảnh khắc ấy, giống như mọi ngày trước khi đi ngủ, mỗi lần thức dậy hay bất cứ lúc nào có một chút thời gian rảnh rỗi, cô bé lại dâng lên một lời cầu nguyện.",
  67: "――Cầu mong người tôi yêu thương luôn được bình an mỗi ngày.",
  68: "△▼△▼△▼△",
  69: "Ánh sáng thổi bay vạn vật, sắc trắng chói lòa thiêu đốt võng mạc của tất cả mọi người.",
  70: "Khi ánh sáng nhạt dần và đôi mắt bị bỏng rát dần hồi phục, tất cả chúng sinh đều chứng kiến hồi kết của Thành phố Quỷ.",
  71: "???: [――――]",
  72: "Tâm chấn của vụ nổ đã sụt xuống, như thể bị khoét đi một vòng tròn hoàn hảo, và tại trung tâm Thành phố Quỷ, nơi đáng lẽ Crimson Lapis Castle tọa lạc, một cái hố khổng lồ đã mở rộng hoác.",
  73: "Cứ như thể cánh tay của một gã khổng lồ đã đào lên cái hố lớn này, một dấu vết rõ ràng chứng minh sự hiện diện của một thực thể đáng sợ đã nuốt chửng toàn bộ Thành phố Quỷ.",
  74: "Và tai ương, thứ đã bị các lực lượng liên minh chiến đấu chống lại, đột ngột biến mất.",
  75: "Đó là kết quả từ quân bài tẩy của Yorna Mishigure, Chủ nhân Thành phố Quỷ, và tất cả những ai tham gia trận chiến đều biết rằng cú hích cuối cùng được thực hiện bởi cô bé đã đánh cược mạng sống của mình.",
  76: "Nói cách khác――",
  77: "???: [――Chúng ta đã được cứu bởi cô bé đó. Ta thật đáng hổ thẹn.]",
  78: "Một người đàn ông lẩm bẩm khi nhìn xuống đáy hố sâu hoắm, giương ra những sợi gai mà hắn điều khiển―― chính là Kafma Irulux.",
  79: "Không hề có sự dối trá; có lẽ, những lời đó xuất phát từ tận đáy lòng hắn. Đúng như phong thái của một chiến binh vượt trội, chàng thanh niên bộc trực tuân theo triết lý của Đế quốc tự trách bản thân vì đã để người khác phải sửa chữa sai lầm của mình.",
  80: "Và điều càng khiến hắn đau lòng hơn là mạng sống của một cô bé đã hy sinh để bù đắp cho điều đó.",
  81: "Kafma: [Ban đầu, ta vốn có hiềm khích với ngươi và đồng bọn của ngươi. Giờ đây mọi chuyện đã lắng xuống, ta thấy thỏa ước đình chiến nên kết thúc tại đây, và chúng ta nên chuyển hướng sang…]",
  82: "???: […Vậy, ngươi muốn chiến đấu với chúng ta?]",
  83: "Kafma: [――. Không nên.]",
  84: "Nhìn lại cái hố lớn phía sau, Kafma lắc đầu trước câu hỏi.",
  85: "Đối mặt với Kafma là Medium, trên lưng mang thanh đại đao quá khổ so với vóc dáng nhỏ bé của cô. Câu hỏi của cô bé lấm lem bùn đất tựa như một tia sáng lấp lánh, ngay cả giữa cảnh hoang tàn đổ nát.",
  86: "Tia sáng tươi đẹp ấy là điều Kafma tin rằng cần thiết để giữ cho tình hình không tồi tệ thêm.",
  87: "Dù sao đi nữa, kết quả cuối cùng là Thành phố Quỷ Chaosflame đã bị hủy diệt, và không một tòa nhà nào còn đứng vững. Kể từ đây, cuộc đấu tranh sinh tồn của những người sống sót sẽ bắt đầu.",
  88: "Dĩ nhiên, vai trò của Kafma với tư cách là Tướng quân Đế quốc là đối phó với những người tị nạn đó và với Yorna Mishigure, người sẽ dẫn dắt họ.",
  89: "Kafma: [Hiện tại, ta đang đi hộ tống cho một nhân vật vô cùng quan trọng. Trước hết, ta phải ưu tiên hội quân với người đó. Mọi chuyện khác lúc này đều không quan trọng.]",
  90: "Medium: [Không quan trọng? Ngươi nói không quan trọng sao? Ta nghĩ nói như vậy thật quá đáng!]",
  91: "Kafma: [Kh-không, ý ta không phải thế…]",
  92: "Nhận phải lời phản đối vì sự vô tình của mình, Kafma hơi chùn bước trước những lời gay gắt của Medium. Nhưng một giọng nói trầm ấm cất lên gọi cô bé giống như cách Kafma gọi, \"Cô nhóc Medium\", đã kịp thời cứu nguy cho hắn.",
  93: "Nhìn về phía họ, đang chậm rãi tiến lại gần là một bóng hình một tay――",
  94: "???: [Đó chỉ là mối bận tâm của gã đó thôi. Gã đang muốn nói rằng mình có việc quan trọng hơn phải làm, nên sẽ không đánh nhau với chúng ta. Vậy nên cứ quyết định như thế đi, được chứ?]",
  95: "Kafma: […Ta không thể tự mình nói gì thêm. Ta sẽ để các ngươi tự diễn giải điều đó.]",
  96: "???: [Này này. Có đầy người giống như anh quanh đây đấy; anh biết đấy, quanh co như anh ở đây này, ông anh.]",
  97: "Nhún vai ngao ngán, người đàn ông một tay―― Al, đứng cạnh Medium. Ngước nhìn gã, mắt Medium mở to kinh ngạc với tiếng \"A\".",
  98: "Và rồi, cô bé chỉ tay vào mặt gã.",
  99: "Medium: [Al-chin, anh thực sự tìm thấy mũ giáp của mình rồi sao nha?]",
  100: "Al: [Ừ, bằng cách nào đó. Nó nằm gần khu vực nơi quán trọ từng tọa lạc, nên cũng là cái may trong cái rủi. Tôi chỉ cần tìm thấy nó thôi, vì tôi biết nó sẽ không bị vỡ.]",
  101: "Medium: [――? Ý anh là nó rất cứng sao nha?]",
  102: "Al: [Ừ ừ, ý tôi là nó rất cứng. Không ai trên đời này có thể phá vỡ nó đâu.]",
  103: "Tuyên bố như thế, Al dùng ngón tay gõ gõ vào chiếc mũ giáp đen kịt gã đang đội. Medium gật đầu đáp lại \"Thật sao~?\", nhưng Kafma lại ném cho Al một cái nhìn sắc lẹm.",
  104: "Nhận ra ánh mắt đó, Al nghiêng đầu hỏi \"Anh muốn làm gì?\".",
  105: "Al: [Ý kiến của anh là anh không muốn đánh nhau với chúng tôi, đúng không? Dĩ nhiên, chúng tôi cũng vậy… Hay nói đúng hơn là tất cả chúng ta đều đã quá kiệt sức vì chuyện đó rồi.]",
  106: "Kafma: [Ngươi đã chỉ huy chúng ta rất xuất sắc trong trận chiến lúc nãy. Tại sao ngươi lại biết trước Great Disaster sẽ di chuyển thế nào?]",
  107: "Al: [Bí mật nghệ nghiệp. Nếu tôi không nói cho anh biết, thì thỏa ước đình chiến sẽ bị hủy bỏ sao?]",
  108: "Kafma: [――. Không, ta sẽ không rút lại lời tuyên bố của mình.]",
  109: "Lắc đầu, Kafma chân thành đáp lại câu trả lời của Al. Hắn sau đó phủi phủi bụi trên chiếc áo choàng rách rưới, quay lưng lại với cả Al và Medium.",
  110: "Hắn hướng về phía người mà hắn đã tuyên bố là nhân vật vô cùng quan trọng.",
  111: "Kafma: [Ta hợp tác với các ngươi lần này là vì tình thế ép buộc. Nhưng ta và các ngươi là kẻ thù… Trừ phi các ngươi thay đổi ý định, chúng ta sẽ gặp lại nhau trên chiến trường. Khi đó, ta sẽ không nương tay đâu.]",
  112: "Al: [Ngay cả khi anh không nói điều đó thì…]",
  113: "Medium: [Chúng tôi cũng vậy thôi…! Cảm ơn vì đã giúp đỡ nha.]",
  114: "Kafma: [Ta chỉ làm những gì ta phải làm với tư cách là Tướng quân Đế quốc.]",
  115: "Nói xong, Kafma dang rộng đôi cánh trong suốt trên tấm lưng cường tráng rồi bay vút đi trong một chuyển động nhanh gọn, tiếng đập cánh phát ra âm thanh vang dội.",
  116: "Medium và Al dõi theo bóng lưng hắn khuất dần, một làn khói bụi bao bọc lấy hắn khi hắn tung cánh bay đi. Khi Kafma biến mất khỏi tầm mắt,",
  117: "Medium: […Al-chin, cảm ơn anh nhiều lắm nha. Thực sự cảm ơn anh. Anh đã cứu mạng tôi đó nha.]",
  118: "Al: [Ồ, đôi bên cùng có lợi thôi mà. Nếu không nhờ sự kiên trì của cô nhóc, cuộc tấn công của thứ khổng lồ đó sẽ thảm khốc hơn nhiều. Sẽ có thêm rất nhiều người chết.]",
  119: "Medium: [Người chết…]",
  120: "Nghe câu trả lời của Al, Medium khẽ nhắm mắt lại.",
  121: "Nhìn Medium cúi đầu với vẻ mặt đau đớn khôn nguôi, Al lấy ngón tay nghịch nghịch khe hở trên kính chắn gió của chiếc mũ giáp, rồi nói:",
  122: "Al: [Tôi biết cô nhóc không hiểu ý tôi, và tôi biết điều này không có nhiều tác dụng an ủi, nhưng nếu con bé đó… Nếu Tanza không làm vậy, chúng ta đã bị quét sạch rồi. Chắc chắn luôn.]",
  123: "Medium: [Có lẽ, anh biết đấy, chúng ta đã có thể cố gắng hơn nữa nha.]",
  124: "Al: [Không, cách đó không hiệu quả đâu. ――Mọi nỗ lực thử nghiệm đều đã tan thành mây khói rồi.]",
  125: "Những lời của Al thất vọng thực sự không có ý nghĩa gì với Medium. Tuy nhiên, cô bé sẽ là nói dối nếu bảo rằng chúng không mang lại chút an ủi nào.",
  126: "Cô bé hiểu rằng Al nói vậy là để an ủi Medium. Nên đó là sự an ủi chân thành.",
  127: "Medium: [Cảm ơn anh nha, Al-chin.]",
  128: "Al: […Không có gì.]",
  129: "Những lời Al đáp lại, một lần nữa, chẳng có nghĩa lý gì với Medium.",
  130: "△▼△▼△▼△",
  131: "???: [Ngươi đã thông suốt những gì cần phải làm chưa, Yorna Mishigure?]",
  132: "Yorna: […Là ngài sao?]",
  133: "Những đống đổ nát, tàn tích đổ nát của các tòa nhà và một cái hố khổng lồ không tưởng đã được tạo ra sau trận chiến khốc liệt.",
  134: "Trong lúc Yorna đứng trên đỉnh đồi, quan sát cảnh tượng đầy những vết sẹo còn sót lại sau khi Thành phố Quỷ Chaosflame dốc toàn lực chiến đấu chống lại Great Disaster, một người đàn ông xuất hiện phía dưới cô.",
  135: "Abel, gương mặt ẩn sau mặt nạ quỷ, hỏi về cảm xúc của cô bằng một tông giọng hoàn toàn không có lấy một chút cảm xúc nào.",
  136: "Không vội vã, Abel bước đi trên đống đổ nát, muốn ngắm nhìn cùng một cảnh tượng với Yorna; tuy nhiên, không hề để chút cảm xúc nào lọt vào giọng nói, hắn cất lời:",
  137: "Abel: [Những gì ta có thể đề nghị cho ngươi chính xác là những gì ta đã viết trong mật thư. Hãy cho ta nghe câu trả lời của ngươi.]",
  138: "Yorna: [Đó thực sự là những gì ngài nên nói khi nhìn vào cảnh tượng bi thương này sao?]",
  139: "Abel: [Lời an ủi sẽ mang lại chỗ trú chân, hay sự thương hại sẽ tạo ra nơi ẩn náu sao? Ngươi và ta đều sinh ra trong số những kẻ có quyền thế, là một phần của những kẻ đã chọn nghĩa vụ của mình. Vì vậy, một giây của chúng ta không có giá trị tương đương với một giây của những kẻ khác.]",
  140: "Yorna: [――――]",
  141: "Không mong cầu sự an ủi, cũng không cần sự đồng cảm; hắn là kẻ đã chọn cách sống đó.",
  142: "Hiểu được điều đó, Yorna kìm chế không phản kháng lại thái độ của hắn. Quan trọng nhất, Yorna sẽ không đạt được gì nếu đối đầu với hắn ở đây chỉ vì lý do cảm xúc.",
  143: "Yorna: [Hôm nay thiếp đã mất mát quá nhiều rồi.]",
  144: "Abel: [Thành phố, và người dân của nó. Sẽ là sai lầm nếu cộng thêm khoảng thời gian ngươi trì hoãn vấn đề này vào những tổn thất đó.]",
  145: "Yorna: [Con bé tên là Tanza.]",
  146: "Abel: [――――]",
  147: "Yorna: [Đứa trẻ yêu quý đã hy sinh thân mình để cứu chúng ta đến cuối cùng… Tên con bé là Tanza.]",
  148: "Nói xong, Yorna rút chiếc obidome từ chiếc kimono của mình ra và đưa cho Abel xem. [1]",
  149: "Abel liếc nhìn cô một cái khi cô xoa nhẹ nó theo vòng tròn, lặng lẽ hỏi về ý định của cô. Đuôi mắt Yorna khẽ cụp xuống trước ánh nhìn dò xét đó,",
  150: "Yorna: [Chiếc obidome này được làm từ sừng của chị gái con bé. Khi khóc thương bên thi thể của chị mình, Tanza đã làm nó cho thiếp… và ngoài chuyện đó ra…]",
  151: "Abel: [――――]",
  152: "Yorna: [Cả những chiếc trâm cài và kanzashi này đều là cống vật từ những đứa trẻ yêu quý của thiếp. Đây là dấu vết của những đứa trẻ bị xua đuổi khỏi quê hương, những đứa trẻ không có gì cả, và đã dâng hiến bản thân để đền đáp thiếp.]",
  153: "Những món trang sức sặc sỡ, những chiếc trâm cài, kanzashi đều là cống vật từ những cư dân của Thành phố Quỷ.",
  154: "Người thì bóc vảy, người thì thu nhặt lông vũ, người thì mài giũa sừng và nanh của mình, chỉ để dâng chúng cho Yorna, cách sống và lòng biết ơn của họ đã định hình nên chúng.",
  155: "Với Yorna, chúng còn giá trị hơn bất kỳ loại đá quý hay kho báu nào, và vì đã được ban tặng những thứ như thế, cô cảm thấy mình phải sống xứng đáng với tình yêu của họ.",
  156: "Thế nhưng――",
  157: "Yorna: [Thiếp không thể phạm thêm bất kỳ sai lầm nào trong lời hứa của mình nữa…]",
  158: "Abel: [――. Sớm muộn gì, Vincent Vollachia đã thoái vị và phe cánh của hắn cũng sẽ bắt đầu hành động. Chúng sẽ không hành động ở đây trong tình cảnh này, nhưng đó chỉ là vấn đề thời gian. Không có thời gian để lãng phí đâu.]",
  159: "Yorna: [Ngài sẽ làm gì với nơi mà những đứa trẻ của thiếp sẽ đi tới?]",
  160: "Abel: [Trước mắt chúng ta không còn lựa chọn nào khác ngoài việc sử dụng Fortress City làm căn cứ. Trên đường đi, chúng ta sẽ chiếm lĩnh các thị trấn khác và đưa chúng vào dưới trướng của mình. Có ngươi và cư dân của Thành phố Quỷ, điều đó hoàn toàn khả thi.]"
};

for (const item of rawData) {
  if (translations[item.id] !== undefined) {
    item.vi = translations[item.id];
  }
}

// Temp save file, will be merged later
const partPath = path.join(__dirname, 'translation_temp', 'ch60_part1.json');
fs.writeFileSync(partPath, JSON.stringify(rawData.filter(x => x.id <= 160), null, 2), 'utf-8');
console.log("Saved part 1 to", partPath);
